#pragma once
#include "glwpp/gl/api/gl_15.hpp"

namespace glwpp::gl {

bool LoadGl_20(LoadFunc func);
 
extern void (*AttachShader)(GLuint program, GLuint shader);
extern void (*BindAttribLocation)(GLuint program, GLuint index, const GLchar * name);
extern void (*BlendEquationSeparate)(GLenum modeRGB, GLenum modeAlpha);
extern void (*CompileShader)(GLuint shader);
extern GLuint (*CreateProgram)();
extern GLuint (*CreateShader)(GLenum type);
extern void (*DeleteProgram)(GLuint program);
extern void (*DeleteShader)(GLuint shader);
extern void (*DetachShader)(GLuint program, GLuint shader);
extern void (*DisableVertexAttribArray)(GLuint index);
extern void (*DrawBuffers)(GLsizei n, const GLenum * bufs);
extern void (*EnableVertexAttribArray)(GLuint index);
extern void (*GetActiveAttrib)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name);
extern void (*GetActiveUniform)(GLuint program, GLuint index, GLsizei bufSize, GLsizei * length, GLint * size, GLenum * type, GLchar * name);
extern void (*GetAttachedShaders)(GLuint program, GLsizei maxCount, GLsizei * count, GLuint * shaders);
extern GLint (*GetAttribLocation)(GLuint program, const GLchar * name);
extern void (*GetProgramInfoLog)(GLuint program, GLsizei bufSize, GLsizei * length, GLchar * infoLog);
extern void (*GetProgramiv)(GLuint program, GLenum pname, GLint * params);
extern void (*GetShaderInfoLog)(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * infoLog);
extern void (*GetShaderSource)(GLuint shader, GLsizei bufSize, GLsizei * length, GLchar * source);
extern void (*GetShaderiv)(GLuint shader, GLenum pname, GLint * params);
extern GLint (*GetUniformLocation)(GLuint program, const GLchar * name);
extern void (*GetUniformfv)(GLuint program, GLint location, GLfloat * params);
extern void (*GetUniformiv)(GLuint program, GLint location, GLint * params);
extern void (*GetVertexAttribPointerv)(GLuint index, GLenum pname, void ** pointer);
extern void (*GetVertexAttribdv)(GLuint index, GLenum pname, GLdouble * params);
extern void (*GetVertexAttribfv)(GLuint index, GLenum pname, GLfloat * params);
extern void (*GetVertexAttribiv)(GLuint index, GLenum pname, GLint * params);
extern GLboolean (*IsProgram)(GLuint program);
extern GLboolean (*IsShader)(GLuint shader);
extern void (*LinkProgram)(GLuint program);
extern void (*ShaderSource)(GLuint shader, GLsizei count, const GLchar *const* string, const GLint * length);
extern void (*StencilFuncSeparate)(GLenum face, GLenum func, GLint ref, GLuint mask);
extern void (*StencilMaskSeparate)(GLenum face, GLuint mask);
extern void (*StencilOpSeparate)(GLenum face, GLenum sfail, GLenum dpfail, GLenum dppass);
extern void (*Uniform1f)(GLint location, GLfloat v0);
extern void (*Uniform1fv)(GLint location, GLsizei count, const GLfloat * value);
extern void (*Uniform1i)(GLint location, GLint v0);
extern void (*Uniform1iv)(GLint location, GLsizei count, const GLint * value);
extern void (*Uniform2f)(GLint location, GLfloat v0, GLfloat v1);
extern void (*Uniform2fv)(GLint location, GLsizei count, const GLfloat * value);
extern void (*Uniform2i)(GLint location, GLint v0, GLint v1);
extern void (*Uniform2iv)(GLint location, GLsizei count, const GLint * value);
extern void (*Uniform3f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2);
extern void (*Uniform3fv)(GLint location, GLsizei count, const GLfloat * value);
extern void (*Uniform3i)(GLint location, GLint v0, GLint v1, GLint v2);
extern void (*Uniform3iv)(GLint location, GLsizei count, const GLint * value);
extern void (*Uniform4f)(GLint location, GLfloat v0, GLfloat v1, GLfloat v2, GLfloat v3);
extern void (*Uniform4fv)(GLint location, GLsizei count, const GLfloat * value);
extern void (*Uniform4i)(GLint location, GLint v0, GLint v1, GLint v2, GLint v3);
extern void (*Uniform4iv)(GLint location, GLsizei count, const GLint * value);
extern void (*UniformMatrix2fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value);
extern void (*UniformMatrix3fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value);
extern void (*UniformMatrix4fv)(GLint location, GLsizei count, GLboolean transpose, const GLfloat * value);
extern void (*UseProgram)(GLuint program);
extern void (*ValidateProgram)(GLuint program);
extern void (*VertexAttrib1d)(GLuint index, GLdouble x);
extern void (*VertexAttrib1dv)(GLuint index, const GLdouble * v);
extern void (*VertexAttrib1f)(GLuint index, GLfloat x);
extern void (*VertexAttrib1fv)(GLuint index, const GLfloat * v);
extern void (*VertexAttrib1s)(GLuint index, GLshort x);
extern void (*VertexAttrib1sv)(GLuint index, const GLshort * v);
extern void (*VertexAttrib2d)(GLuint index, GLdouble x, GLdouble y);
extern void (*VertexAttrib2dv)(GLuint index, const GLdouble * v);
extern void (*VertexAttrib2f)(GLuint index, GLfloat x, GLfloat y);
extern void (*VertexAttrib2fv)(GLuint index, const GLfloat * v);
extern void (*VertexAttrib2s)(GLuint index, GLshort x, GLshort y);
extern void (*VertexAttrib2sv)(GLuint index, const GLshort * v);
extern void (*VertexAttrib3d)(GLuint index, GLdouble x, GLdouble y, GLdouble z);
extern void (*VertexAttrib3dv)(GLuint index, const GLdouble * v);
extern void (*VertexAttrib3f)(GLuint index, GLfloat x, GLfloat y, GLfloat z);
extern void (*VertexAttrib3fv)(GLuint index, const GLfloat * v);
extern void (*VertexAttrib3s)(GLuint index, GLshort x, GLshort y, GLshort z);
extern void (*VertexAttrib3sv)(GLuint index, const GLshort * v);
extern void (*VertexAttrib4Nbv)(GLuint index, const GLbyte * v);
extern void (*VertexAttrib4Niv)(GLuint index, const GLint * v);
extern void (*VertexAttrib4Nsv)(GLuint index, const GLshort * v);
extern void (*VertexAttrib4Nub)(GLuint index, GLubyte x, GLubyte y, GLubyte z, GLubyte w);
extern void (*VertexAttrib4Nubv)(GLuint index, const GLubyte * v);
extern void (*VertexAttrib4Nuiv)(GLuint index, const GLuint * v);
extern void (*VertexAttrib4Nusv)(GLuint index, const GLushort * v);
extern void (*VertexAttrib4bv)(GLuint index, const GLbyte * v);
extern void (*VertexAttrib4d)(GLuint index, GLdouble x, GLdouble y, GLdouble z, GLdouble w);
extern void (*VertexAttrib4dv)(GLuint index, const GLdouble * v);
extern void (*VertexAttrib4f)(GLuint index, GLfloat x, GLfloat y, GLfloat z, GLfloat w);
extern void (*VertexAttrib4fv)(GLuint index, const GLfloat * v);
extern void (*VertexAttrib4iv)(GLuint index, const GLint * v);
extern void (*VertexAttrib4s)(GLuint index, GLshort x, GLshort y, GLshort z, GLshort w);
extern void (*VertexAttrib4sv)(GLuint index, const GLshort * v);
extern void (*VertexAttrib4ubv)(GLuint index, const GLubyte * v);
extern void (*VertexAttrib4uiv)(GLuint index, const GLuint * v);
extern void (*VertexAttrib4usv)(GLuint index, const GLushort * v);
extern void (*VertexAttribPointer)(GLuint index, GLint size, GLenum type, GLboolean normalized, GLsizei stride, const void * pointer);

}