#pragma once
#include "glwpp/gl/api/gl_40.hpp"

namespace glwpp::gl {

bool LoadGl_41(LoadFunc func);

extern void (*ActiveShaderProgram)(UInt pipeline, UInt program);
extern void (*BindProgramPipeline)(UInt pipeline);
extern void (*ClearDepthf)(Float d);
extern UInt (*CreateShaderProgramv)(Enum type, Sizei count, const Char *const* strings);
extern void (*DeleteProgramPipelines)(Sizei n, const UInt * pipelines);
extern void (*DepthRangeArrayv)(UInt first, Sizei count, const Double * v);
extern void (*DepthRangeIndexed)(UInt index, Double n, Double f);
extern void (*DepthRangef)(Float n, Float f);
extern void (*GenProgramPipelines)(Sizei n, UInt * pipelines);
extern void (*GetDoublei_v)(Enum target, UInt index, Double * data);
extern void (*GetFloati_v)(Enum target, UInt index, Float * data);
extern void (*GetProgramBinary)(UInt program, Sizei bufSize, Sizei * length, Enum * binaryFormat, void * binary);
extern void (*GetProgramPipelineInfoLog)(UInt pipeline, Sizei bufSize, Sizei * length, Char * infoLog);
extern void (*GetProgramPipelineiv)(UInt pipeline, Enum pname, Int * params);
extern void (*GetShaderPrecisionFormat)(Enum shadertype, Enum precisiontype, Int * range, Int * precision);
extern void (*GetVertexAttribLdv)(UInt index, Enum pname, Double * params);
extern Bool (*IsProgramPipeline)(UInt pipeline);
extern void (*ProgramBinary)(UInt program, Enum binaryFormat, const void * binary, Sizei length);
extern void (*ProgramParameteri)(UInt program, Enum pname, Int value);
extern void (*ProgramUniform1d)(UInt program, Int location, Double v0);
extern void (*ProgramUniform1dv)(UInt program, Int location, Sizei count, const Double * value);
extern void (*ProgramUniform1f)(UInt program, Int location, Float v0);
extern void (*ProgramUniform1fv)(UInt program, Int location, Sizei count, const Float * value);
extern void (*ProgramUniform1i)(UInt program, Int location, Int v0);
extern void (*ProgramUniform1iv)(UInt program, Int location, Sizei count, const Int * value);
extern void (*ProgramUniform1ui)(UInt program, Int location, UInt v0);
extern void (*ProgramUniform1uiv)(UInt program, Int location, Sizei count, const UInt * value);
extern void (*ProgramUniform2d)(UInt program, Int location, Double v0, Double v1);
extern void (*ProgramUniform2dv)(UInt program, Int location, Sizei count, const Double * value);
extern void (*ProgramUniform2f)(UInt program, Int location, Float v0, Float v1);
extern void (*ProgramUniform2fv)(UInt program, Int location, Sizei count, const Float * value);
extern void (*ProgramUniform2i)(UInt program, Int location, Int v0, Int v1);
extern void (*ProgramUniform2iv)(UInt program, Int location, Sizei count, const Int * value);
extern void (*ProgramUniform2ui)(UInt program, Int location, UInt v0, UInt v1);
extern void (*ProgramUniform2uiv)(UInt program, Int location, Sizei count, const UInt * value);
extern void (*ProgramUniform3d)(UInt program, Int location, Double v0, Double v1, Double v2);
extern void (*ProgramUniform3dv)(UInt program, Int location, Sizei count, const Double * value);
extern void (*ProgramUniform3f)(UInt program, Int location, Float v0, Float v1, Float v2);
extern void (*ProgramUniform3fv)(UInt program, Int location, Sizei count, const Float * value);
extern void (*ProgramUniform3i)(UInt program, Int location, Int v0, Int v1, Int v2);
extern void (*ProgramUniform3iv)(UInt program, Int location, Sizei count, const Int * value);
extern void (*ProgramUniform3ui)(UInt program, Int location, UInt v0, UInt v1, UInt v2);
extern void (*ProgramUniform3uiv)(UInt program, Int location, Sizei count, const UInt * value);
extern void (*ProgramUniform4d)(UInt program, Int location, Double v0, Double v1, Double v2, Double v3);
extern void (*ProgramUniform4dv)(UInt program, Int location, Sizei count, const Double * value);
extern void (*ProgramUniform4f)(UInt program, Int location, Float v0, Float v1, Float v2, Float v3);
extern void (*ProgramUniform4fv)(UInt program, Int location, Sizei count, const Float * value);
extern void (*ProgramUniform4i)(UInt program, Int location, Int v0, Int v1, Int v2, Int v3);
extern void (*ProgramUniform4iv)(UInt program, Int location, Sizei count, const Int * value);
extern void (*ProgramUniform4ui)(UInt program, Int location, UInt v0, UInt v1, UInt v2, UInt v3);
extern void (*ProgramUniform4uiv)(UInt program, Int location, Sizei count, const UInt * value);
extern void (*ProgramUniformMatrix2dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix2fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ProgramUniformMatrix2x3dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix2x3fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ProgramUniformMatrix2x4dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix2x4fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ProgramUniformMatrix3dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix3fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ProgramUniformMatrix3x2dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix3x2fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ProgramUniformMatrix3x4dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix3x4fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ProgramUniformMatrix4dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix4fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ProgramUniformMatrix4x2dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix4x2fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ProgramUniformMatrix4x3dv)(UInt program, Int location, Sizei count, Bool transpose, const Double * value);
extern void (*ProgramUniformMatrix4x3fv)(UInt program, Int location, Sizei count, Bool transpose, const Float * value);
extern void (*ReleaseShaderCompiler)();
extern void (*ScissorArrayv)(UInt first, Sizei count, const Int * v);
extern void (*ScissorIndexed)(UInt index, Int left, Int bottom, Sizei width, Sizei height);
extern void (*ScissorIndexedv)(UInt index, const Int * v);
extern void (*ShaderBinary)(Sizei count, const UInt * shaders, Enum binaryFormat, const void * binary, Sizei length);
extern void (*UseProgramStages)(UInt pipeline, BitField stages, UInt program);
extern void (*ValidateProgramPipeline)(UInt pipeline);
extern void (*VertexAttribL1d)(UInt index, Double x);
extern void (*VertexAttribL1dv)(UInt index, const Double * v);
extern void (*VertexAttribL2d)(UInt index, Double x, Double y);
extern void (*VertexAttribL2dv)(UInt index, const Double * v);
extern void (*VertexAttribL3d)(UInt index, Double x, Double y, Double z);
extern void (*VertexAttribL3dv)(UInt index, const Double * v);
extern void (*VertexAttribL4d)(UInt index, Double x, Double y, Double z, Double w);
extern void (*VertexAttribL4dv)(UInt index, const Double * v);
extern void (*VertexAttribLPointer)(UInt index, Int size, Enum type, Sizei stride, const void * pointer);
extern void (*ViewportArrayv)(UInt first, Sizei count, const Float * v);
extern void (*ViewportIndexedf)(UInt index, Float x, Float y, Float w, Float h);
extern void (*ViewportIndexedfv)(UInt index, const Float * v);

}